javascript:
  application:
    require:
      - a_huge_library
  beacons:
  businesses:
  campaigns: 
  customers: 
  greetings: 
  locations: 
  pages:
  subscriptions: 
  receipts:
  admin/receipts: